services:
    kavita:
        image: jvmilazz0/kavita:latest
        container_name: kavita
        volumes:
            - /opt/docker/kavita/books:/kavita/books
            - /opt/docker/kavita/config:/kavita/config
        env_file:
            - ../.env.global
            - .env
        ports:
            - "5000:5000"
        restart: unless-stopped
        user: "${PUID}:${PGID}"

networks:
  default:
    name: kavita_default
