services:
  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    env_file:
       - ../.env.global
       - .env
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
      - "50300:50300/udp"
    volumes:
      - ./volumes/slskd/app:/app
    restart: unless-stopped

  soulsync:
    image: boulderbadgedad/soulsync:latest
    container_name: soulsync
    env_file:
       - ../.env.global
       - .env
    ports:
      - "8008:8008"
    volumes:
      - ./volumes/soulsync/config:/app/config
      - ./volumes/soulsync/logs:/app/logs
      - ./volumes/soulsync/database:/app/data
      - ./volumes/slskd/app/downloads:/app/downloads:rw
      - ./volumes/soulsync/staging:/app/Staging
      - ./volumes/music:/music:rw
    depends_on:
      - slskd
    restart: unless-stopped

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: "${PUID:-1000}:${PGID:-1000}"
    env_file:
       - ../.env.global
       - .env
    ports:
      - "4533:4533"
    volumes:
      - ./volumes/navidrome:/data
      - ./volumes/music:/music:ro
    depends_on:
      - soulsync
    restart: unless-stopped
